CREATE TABLE PUBLIC.DEMO_SESSION
(	SESSION_ID VARCHAR(2000 ) NOT NULL ,
     CREATION_TIME INTEGER NOT NULL ,
     LAST_ACCESS_TIME INTEGER NOT NULL ,
     MAX_INACTIVE_INTERVAL INTEGER NOT NULL ,
     PRINCIPAL_NAME VARCHAR(100),
     CONSTRAINT SESSION_PK PRIMARY KEY (SESSION_ID)
);
CREATE TABLE PUBLIC.DEMO_SESSION_ATTRIBUTES
(	SESSION_ID VARCHAR(2000 ) NOT NULL ,
     ATTRIBUTE_NAME VARCHAR(200 ) NOT NULL ,
     ATTRIBUTE_VALUE VARCHAR(1000 ) NOT NULL ,
     CONSTRAINT SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_ID, ATTRIBUTE_NAME),
     CONSTRAINT SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_ID) REFERENCES PUBLIC.DEMO_SESSION (SESSION_ID) ON DELETE CASCADE ENABLE
);